
using System.Net.Mime;
using CatchUpPlatform.API.News.Application.Services;
using CatchUpPlatform.API.News.Domain.Model.Queries;
using CatchUpPlatform.API.News.Domain.Model.ValueObjects;
using CatchUpPlatform.API.News.Interfaces.REST.Resources;
using CatchUpPlatform.API.News.Interfaces.REST.Transform;
using CatchUpPlatform.API.Resources;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Swashbuckle.AspNetCore.Annotations;

namespace CatchUpPlatform.API.News.Interfaces.REST;

/// <summary>
///     Favorite sources' controller.
/// </summary>
/// <param name="favoriteSourceCommandService">The Favorite Source Command Service</param>
/// <param name="favoriteSourceQueryService">The Favorite Source Query Service</param>
/// <param name="localizer">String localizer for response messages</param>
/// <param name="logger">Logger for diagnostics and error reporting</param>
[ApiController]
[Route("api/v1/[controller]")]
[Produces(MediaTypeNames.Application.Json)]
[Tags("Favorite Sources")]
public class FavoriteSourcesController(
    IFavoriteSourceCommandService favoriteSourceCommandService,
    IFavoriteSourceQueryService favoriteSourceQueryService,
    IStringLocalizer<SharedResource> localizer,
    ILogger<FavoriteSourcesController> logger)
    : ControllerBase
{
    /// <summary>
    ///     Creates a favorite source.
    /// </summary>
    /// <param name="resource">CreateFavoriteSourceResource resource</param>
    /// <param name="cancellationToken">Token to cancel the asynchronous operation.</param>
    /// <returns>
    ///     A response as an action result containing the created favorite source, or bad request if the favorite source was
    ///     not created.
    /// </returns>
    [HttpPost]
    [SwaggerOperation(Summary = "Creates a favorite source",
        OperationId = "CreateFavoriteSource")]
    [SwaggerResponse(201, "Created", typeof(FavoriteSourceResource))]
    [SwaggerResponse(400, "Bad Request", typeof(string))]
    [SwaggerResponse(409, "Conflict", typeof(string))]
    [SwaggerResponse(500, "Server Error", typeof(ProblemDetails))]
    public async Task<ActionResult> CreateFavoriteSource(
        [FromBody] CreateFavoriteSourceResource resource,
        CancellationToken cancellationToken)
    {
        try
        {
            var command = CreateFavoriteSourceCommandFromResourceAssembler
                .ToCommandFromResource(resource);
            var result = await favoriteSourceCommandService
                .Handle(command, cancellationToken);
            return ActionResultFromCreateFavoriteSourceResultAssembler
                .ToActionResultFromCreateFavoriteSourceResult(
                    result, this, localizer, nameof(GetFavoriteSourceById));
        }
        catch (ArgumentException ex)
        {
            logger.LogWarning(ex, "Validation failed");
            return BadRequest(localizer["InvalidFavoriteSourceRequest"].Value);
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Unexpected error");
            return Problem(
                title: localizer["UnexpectedServerError"].Value,
                detail: localizer["UnexpectedErrorCreatingFavoriteSource"].Value,
                statusCode: 500);
        }
    }

    /// <summary>
    ///     Gets all favorite sources by news API key.
    /// </summary>
    /// <param name="newsApiKey">The News API Key generated by the service provider</param>
    /// <param name="cancellationToken">Token to cancel the asynchronous operation.</param>
    /// <returns>
    ///     A response as an action result containing the favorite sources, or not found if no favorite sources were found.
    /// </returns>
    private async Task<ActionResult> GetAllFavoriteSourcesByNewsApiKey(
        NewsApiKey newsApiKey, CancellationToken ct)
    {
        var query = new GetAllFavoriteSourcesByNewsApiKeyQuery(newsApiKey);
        var result = await favoriteSourceQueryService.Handle(query, ct);
        return Ok(result.Select(
            FavoriteSourceResourceFromEntityAssembler.ToResourceFromEntity));
    }

    /// <summary>
    ///     Gets a favorite source by news API key and source id.
    /// </summary>
    /// <param name="newsApiKey">The News API Key generated by the news service provider</param>
    /// <param name="sourceId">The Source ID from the news service provider</param>
    /// <param name="cancellationToken">Token to cancel the asynchronous operation.</param>
    /// <returns>
    ///     A response as an action result containing the favorite source, or not found if the favorite source was not found.
    /// </returns>
    private async Task<ActionResult> GetFavoriteSourceByNewsApiKeyAndSourceId(
        NewsApiKey newsApiKey, SourceId sourceId, CancellationToken ct)
    {
        var query = new GetFavoriteSourceByNewsApiKeyAndSourceIdQuery(newsApiKey, sourceId);
        var result = await favoriteSourceQueryService.Handle(query, ct);
        if (result is null) return NotFound();
        return Ok(FavoriteSourceResourceFromEntityAssembler.ToResourceFromEntity(result));
    }

    /// <summary>
    ///     Gets a favorite source according to parameters.
    /// </summary>
    /// <param name="newsApiKey">The News API Key generated by the news service provider</param>
    /// <param name="sourceId">The Source ID from the news service provider</param>
    /// <param name="cancellationToken">Token to cancel the asynchronous operation.</param>
    /// <returns>
    ///     A response as an action result containing the favorite source if News API Key and Source ID are provided,
    ///     or a response with the favorite sources for the News API Key if Source ID is not present.
    /// </returns>
    [HttpGet]
    [SwaggerOperation(Summary = "Gets favorite sources by query params",
        OperationId = "GetFavoriteSourceFromQuery")]
    [SwaggerResponse(200, "OK")]
    [SwaggerResponse(400, "Bad Request", typeof(string))]
    [SwaggerResponse(404, "Not Found")]
    public async Task<ActionResult> GetFavoriteSourceFromQuery(
        [FromQuery] string newsApiKey,
        [FromQuery] string? sourceId = null,
        CancellationToken cancellationToken = default)
    {
        try
        {
            var newsApiKeyVO = new NewsApiKey(newsApiKey);
            return string.IsNullOrEmpty(sourceId)
                ? await GetAllFavoriteSourcesByNewsApiKey(newsApiKeyVO, cancellationToken)
                : await GetFavoriteSourceByNewsApiKeyAndSourceId(
                    newsApiKeyVO, new SourceId(sourceId), cancellationToken);
        }
        catch (ArgumentException ex)
        {
            logger.LogWarning(ex, "Validation failed for query");
            return BadRequest(localizer["InvalidFavoriteSourceQuery"].Value);
        }
    }

    /// <summary>
    ///     Gets a favorite source by id.
    /// </summary>
    /// <param name="id">The Favorite Source ID</param>
    /// <param name="cancellationToken">Token to cancel the asynchronous operation.</param>
    /// <returns>
    ///     A response as an action result containing the favorite source, or not found if the favorite source was not found.
    /// </returns>
    [HttpGet("{id}")]
    [SwaggerOperation(Summary = "Gets a favorite source by id",
        OperationId = "GetFavoriteSourceById")]
    [SwaggerResponse(200, "OK", typeof(FavoriteSourceResource))]
    [SwaggerResponse(404, "Not Found")]
    public async Task<ActionResult> GetFavoriteSourceById(
        int id, CancellationToken cancellationToken = default)
    {
        var query = new GetFavoriteSourceByIdQuery(id);
        var result = await favoriteSourceQueryService.Handle(query, cancellationToken);
        if (result is null) return NotFound();
        return Ok(FavoriteSourceResourceFromEntityAssembler.ToResourceFromEntity(result));
    }
}

