// <auto-generated />
using System;
using CatchUpPlatform.API.Shared.Infrastructure.Persistence.EFC.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatchUpPlatform.API.Shared.Infrastructure.Persistence.EFC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260530190032_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CatchUpPlatform.API.News.Domain.Model.Aggregates.FavoriteSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("NewsApiKey")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("news_api_key");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("source_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_favorite_sources");

                    b.HasIndex("NewsApiKey", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("i_x_favorite_sources_news_api_key_source_id");

                    b.ToTable("favorite_sources");
                });
#pragma warning restore 612, 618
        }
    }
}
